import { AppProvider } from "@/components";
import { cn } from "@/utils/functions";
import { fonts } from "@/fonts";
import "@/css/globals.css";

import type { ReactNode } from "react";
import type { Metadata } from "next";
import type { IRSC } from "@/types";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<IRSC>): ReactNode {
	return (
		<html lang="en">
			<body className={cn(fonts, `antialiased`)}>
				<AppProvider>{children}</AppProvider>
			</body>
		</html>
	);
}
