import AppProvider from "@/components/providers/AppProvider";
import { notFound } from "next/navigation";
import { locales } from "@/i18n/routing";
import { cn } from "@/utils/functions";
import { hasLocale } from "next-intl";
import { fonts } from "@/fonts";
import "@/css/globals.css";

import type { ReactNode } from "react";
import type { Metadata } from "next";
import type { ITRSC } from "@/types";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Readonly<ITRSC>): Promise<ReactNode> {
	const { locale = "en" } = await params;

	if (!hasLocale(locales, locale)) notFound();

	return (
		<html lang="en">
			<head>
				<script crossOrigin="anonymous" src="//unpkg.com/react-scan/dist/auto.global.js" />
			</head>
			<body className={cn(fonts, `antialiased`)}>
				<AppProvider>{children}</AppProvider>
			</body>
		</html>
	);
}
