import { geistMono, geistSans } from "@/fonts";
import "@/css/globals.css";

import type { ReactNode } from "react";
import type { Metadata } from "next";
import type { IRSC } from "@/types";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<IRSC>): ReactNode {
	const fonts = `${geistSans.variable} ${geistMono.variable}`;
	return (
		<html lang="en">
			<body className={cn(fonts, `antialiased`)}>{children}</body>
		</html>
	);
}
